/*Copyright (c) 2015-2016 imaginea-com All Rights Reserved.
 This software is the confidential and proprietary information of imaginea-com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with imaginea-com*/
package com.test_098.adventureworks2012;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.Type;
import org.joda.time.LocalDateTime;

/**
 * ErrorLog generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`ErrorLog`")
public class ErrorLog implements Serializable {

    private Integer errorLogId;
    private Integer errorLine;
    private String errorMessage;
    private int errorNumber;
    private String errorProcedure;
    private Integer errorSeverity;
    private Integer errorState;
    @Type(type = "DateTime")
    private LocalDateTime errorTime;
    private String userName;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "`ErrorLogID`", nullable = false, scale = 0, precision = 10)
    public Integer getErrorLogId() {
        return this.errorLogId;
    }

    public void setErrorLogId(Integer errorLogId) {
        this.errorLogId = errorLogId;
    }

    @Column(name = "`ErrorLine`", nullable = true, scale = 0, precision = 10)
    public Integer getErrorLine() {
        return this.errorLine;
    }

    public void setErrorLine(Integer errorLine) {
        this.errorLine = errorLine;
    }

    @Column(name = "`ErrorMessage`", nullable = false, length = 255)
    public String getErrorMessage() {
        return this.errorMessage;
    }

    public void setErrorMessage(String errorMessage) {
        this.errorMessage = errorMessage;
    }

    @Column(name = "`ErrorNumber`", nullable = false, scale = 0, precision = 10)
    public int getErrorNumber() {
        return this.errorNumber;
    }

    public void setErrorNumber(int errorNumber) {
        this.errorNumber = errorNumber;
    }

    @Column(name = "`ErrorProcedure`", nullable = true, length = 255)
    public String getErrorProcedure() {
        return this.errorProcedure;
    }

    public void setErrorProcedure(String errorProcedure) {
        this.errorProcedure = errorProcedure;
    }

    @Column(name = "`ErrorSeverity`", nullable = true, scale = 0, precision = 10)
    public Integer getErrorSeverity() {
        return this.errorSeverity;
    }

    public void setErrorSeverity(Integer errorSeverity) {
        this.errorSeverity = errorSeverity;
    }

    @Column(name = "`ErrorState`", nullable = true, scale = 0, precision = 10)
    public Integer getErrorState() {
        return this.errorState;
    }

    public void setErrorState(Integer errorState) {
        this.errorState = errorState;
    }

    @Column(name = "`ErrorTime`", nullable = false)
    public LocalDateTime getErrorTime() {
        return this.errorTime;
    }

    public void setErrorTime(LocalDateTime errorTime) {
        this.errorTime = errorTime;
    }

    @Column(name = "`UserName`", nullable = false, length = 255)
    public String getUserName() {
        return this.userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ErrorLog)) return false;
        final ErrorLog errorLog = (ErrorLog) o;
        return Objects.equals(getErrorLogId(), errorLog.getErrorLogId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getErrorLogId());
    }
}

